from ListModel import ListModel


class Country(ListModel):

    def __init__(self):
        super(Country, self).__init__()
        self.__country_list = ['united kingdom', 'uk', 'united states', 'usa', 'eeuu', 'estados unidos', 'uae',
                               'ukraine', 'singapore', 'italy', 'hong kong', 'turkey', 'belarus', 'netherlands',
                               'united arab amirates', 'statele unite', 'india', 'qatar', 'china', 'cyprus',
                               'costa rica', 'brazil', 'uganda', 'russia', 'greece',
                               'afghanistan', 'albania', 'algeria', 'american samoa', 'andorra', 'angola', 'anguilla',
                               'antigua and barbuda',
                               'argentina', 'armenia', 'aruba', 'australia', 'austria', 'azerbaijan', 'bahamas',
                               'bahrain', 'bangladesh',
                               'barbados', 'belarus', 'belgium', 'belize', 'benin', 'bermuda', 'bhutan', 'bolivia',
                               'bonaire', 'bosnia-herzegovina',
                               'botswana', 'bouvet island', 'brazil', 'brunei', 'bulgaria', 'burkina faso', 'burundi',
                               'cambodia', 'cameroon',
                               'canada', 'cape verde', 'cayman islands', 'central african republic', 'chad', 'chile',
                               'china', 'christmas island',
                               'cocos (keeling) islands', 'colombia', 'comoros',
                               'congo, democratic republic of the (zaire)', 'congo, republic of',
                               'cook islands', 'costa rica', 'croatia', 'cuba', 'curacao', 'cyprus', 'czech republic',
                               'denmark', 'djibouti',
                               'dominica', 'dominican republic', 'ecuador', 'egypt', 'el salvador', 'equatorial guinea',
                               'eritrea', 'estonia',
                               'ethiopia', 'falkland islands', 'faroe islands', 'fiji', 'finland', 'france',
                               'french guiana', 'gabon', 'gambia',
                               'georgia', 'germany', 'ghana', 'gibraltar', 'greece', 'greenland', 'grenada',
                               'guadeloupe (french)', 'guam (usa)',
                               'guatemala', 'guinea', 'guinea bissau', 'guyana', 'haiti', 'holy see', 'honduras',
                               'hong kong', 'hungary', 'iceland',
                               'india', 'indonesia', 'iran', 'iraq', 'ireland', 'israel', 'italy',
                               'ivory coast (cote d`ivoire)', 'jamaica', 'japan',
                               'jordan', 'kazakhstan', 'kenya', 'kiribati', 'kosovo', 'kuwait', 'kyrgyzstan', 'laos',
                               'latvia', 'lebanon', 'lesotho',
                               'liberia', 'libya', 'liechtenstein', 'lithuania', 'luxembourg', 'macau', 'macedonia',
                               'madagascar', 'malawi', 'malaysia',
                               'maldives', 'mali', 'malta', 'marshall islands', 'martinique (french)', 'mauritania',
                               'mauritius', 'mayotte', 'mexico',
                               'micronesia', 'moldova', 'monaco', 'mongolia', 'montenegro', 'montserrat', 'morocco',
                               'mozambique', 'myanmar', 'namibia',
                               'nauru', 'nepal', 'netherlands', 'netherlands antilles', 'new caledonia (french)',
                               'new zealand', 'nicaragua', 'niger',
                               'nigeria', 'niue', 'norfolk island', 'north korea', 'northern mariana islands', 'norway',
                               'oman', 'pakistan', 'palau',
                               'panama', 'papua new guinea', 'paraguay', 'peru', 'philippines', 'pitcairn island',
                               'poland', 'polynesia (french)',
                               'portugal', 'puerto rico', 'qatar', 'reunion', 'romania', 'russia', 'rwanda',
                               'saint helena', 'saint kitts and nevis',
                               'saint lucia', 'saint pierre and miquelon', 'saint vincent and grenadines', 'samoa',
                               'san marino',
                               'sao tome and principe', 'saudi arabia', 'senegal', 'serbia', 'seychelles',
                               'sierra leone', 'singapore',
                               'sint maarten', 'slovakia', 'slovenia', 'solomon islands', 'somalia', 'south africa',
                               'south georgia and south sandwich islands', 'south korea', 'south sudan', 'south sudan',
                               'spain', 'sri lanka', 'sudan', 'suriname', 'svalbard and jan mayen islands', 'swaziland',
                               'sweden',
                               'switzerland', 'syria', 'taiwan', 'tajikistan', 'tanzania', 'thailand',
                               'timor-leste (east timor)', 'togo',
                               'tokelau', 'tonga', 'trinidad and tobago', 'tunisia', 'turkey', 'turkmenistan',
                               'turks and caicos islands',
                               'tuvalu', 'uganda', 'ukraine', 'united arab emirates', 'united kingdom', 'united states',
                               'uruguay', 'uzbekistan',
                               'vanuatu', 'venezuela', 'vietnam', 'virgin islands', 'wallis and futuna islands',
                               'yemen', 'zambia', 'zimbabwe']

        self.setList(self.__country_list)
        self.setStrict(False)
